-- Control-plane tables (data-model.md, ADR-0002). Workflow state survives restart (FR-ORC-006).

CREATE TABLE workflow_run (
    id                   UUID          PRIMARY KEY,
    correlation_id       VARCHAR(64),
    original_requirement VARCHAR(4000) NOT NULL,
    current_requirement  VARCHAR(8000),
    normalized_json      CLOB,
    change_type          VARCHAR(16),
    status               VARCHAR(32)   NOT NULL,
    pending_action       VARCHAR(64),
    plan_version         INT           NOT NULL,
    policy_version       VARCHAR(16)   NOT NULL,
    recoverable          BOOLEAN,
    stop_reason          VARCHAR(1000),
    fault_plan_json      CLOB,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at             TIMESTAMP WITH TIME ZONE,
    version              BIGINT        NOT NULL
);

CREATE TABLE workflow_stage (
    run_id         UUID          NOT NULL REFERENCES workflow_run (id),
    node           VARCHAR(32)   NOT NULL,
    status         VARCHAR(16)   NOT NULL,
    attempts       INT           NOT NULL,
    started_at     TIMESTAMP WITH TIME ZONE,
    ended_at       TIMESTAMP WITH TIME ZONE,
    thread_name    VARCHAR(64),
    output_json    CLOB,
    provenance     VARCHAR(16),
    failure_class  VARCHAR(16),
    failure_code   VARCHAR(32),
    failure_reason VARCHAR(1000),
    plan_version   INT           NOT NULL,
    PRIMARY KEY (run_id, node)
);

CREATE TABLE decision (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         UUID          NOT NULL REFERENCES workflow_run (id),
    type           VARCHAR(32)   NOT NULL,
    gate           VARCHAR(48),
    actor_type     VARCHAR(8)    NOT NULL,
    actor_identity VARCHAR(100)  NOT NULL,
    reason         VARCHAR(2000) NOT NULL,
    plan_version   INT           NOT NULL,
    supersedes_id  BIGINT        REFERENCES decision (id),
    payload_json   CLOB,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE policy_evaluation (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                 UUID          NOT NULL REFERENCES workflow_run (id),
    policy_version         VARCHAR(16)   NOT NULL,
    check_id               VARCHAR(16)   NOT NULL,
    domain                 VARCHAR(32)   NOT NULL,
    node                   VARCHAR(32)   NOT NULL,
    mandatory              BOOLEAN       NOT NULL,
    result                 VARCHAR(24)   NOT NULL,
    reason                 VARCHAR(2000),
    plan_version           INT           NOT NULL,
    resolution_decision_id BIGINT        REFERENCES decision (id),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Append-only: the application only ever inserts into this table (FR-OBS-002, ADR-0002).
CREATE TABLE audit_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         UUID          NOT NULL REFERENCES workflow_run (id),
    correlation_id VARCHAR(64),
    seq            INT           NOT NULL,
    type           VARCHAR(40)   NOT NULL,
    node           VARCHAR(32),
    actor_type     VARCHAR(8)    NOT NULL,
    actor_identity VARCHAR(100)  NOT NULL,
    plan_version   INT           NOT NULL,
    policy_version VARCHAR(16)   NOT NULL,
    injected       BOOLEAN       NOT NULL,
    payload_json   CLOB,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_audit_event_run_seq UNIQUE (run_id, seq)
);
