-- Application-plane tables (data-model.md, ADR-0002). No expiration column: it is added only by the
-- SCN-B brownfield migration after its design approval.

CREATE TABLE link (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(16)   NOT NULL,
    original_url     VARCHAR(2048) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    redirect_count   BIGINT        DEFAULT 0 NOT NULL,
    last_redirect_at TIMESTAMP WITH TIME ZONE,
    probe_run_id     UUID,
    CONSTRAINT uk_link_code UNIQUE (code)
);

CREATE INDEX ix_link_probe_run_id ON link (probe_run_id);

CREATE TABLE idempotency_record (
    idem_key            VARCHAR(100) PRIMARY KEY,
    request_fingerprint CHAR(64)     NOT NULL,
    link_id             BIGINT       NOT NULL REFERENCES link (id),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
